Repository CSI-SCT-SB/Extra-Mile, pull requests merged in 2022-10, with the labels that each got.

#1 Create Matrix_add.c
  C/Matrix_add.c
  C/Source_code.c
Labels: Hacktoberfest-accepted

#3 Update
  C/BMI.c
  PYTHON/SimpleCalculator.ipynb
Labels: Hacktoberfest-accepted

#4 Numberpyramid.c
  C/Numberpyramid.c
  JAVA/simplepyramid.java
  PYTHON/Invertedpyramid.py
  RUST/simplerustcode.rs
Labels: Hacktoberfest-accepted

#6 fullpyramidof*.c
  C/fullpyramidof*.c
Labels: good first issue, Hacktoberfest-accepted

#7 Create jpg2ascii.py
  PYTHON/jpg2ascii.py
Labels: Hacktoberfest-accepted

#9 Fibonacci.java
  JAVA/Fibonacci.c
Labels: Hacktoberfest-accepted

#11 Inverted Pyramid
  PYTHON/InvertedPyramid.ipynb
  PYTHON/Invertedpyramid.py
  PYTHON/Turtle_code.py
Labels: Hacktoberfest-accepted

#13 Temperature Scale Conversions
  C/TemperatureScaleConverter.c
  PYTHON/Turtle_code.py
Labels: Hacktoberfest-accepted

#14 parenthesis balance check using stack
  C/ParenthesisBalancing.c
Labels: Hacktoberfest-accepted

#15 prime.ipynb
  C/palindrome.c
  PYTHON/prime.ipynb
  prime.ipynb
Labels: Hacktoberfest-accepted

#18 lexicographicsort.c
  C/lexicographicsort.c
  JAVA/pascal.java
  PYTHON/valid.py
Labels: Hacktoberfest-accepted

#19 Create calculator.java
  JAVA/calculator.java
Labels: Hacktoberfest-accepted

#23 Create encodebase64.rs
  RUST/encodebase64.rs
Labels: Hacktoberfest-accepted, BIG SHOT

#24 A Python Program to illustrate set and list comprehension.
  PYTHON/Set&list_Comprehensions.ipynb
Labels: Hacktoberfest-accepted

#25 Polygon drawing Using Turtle
  PYTHON/Turtle_Polygon_Drawing.ipynb
Labels: Hacktoberfest-accepted

#26 valid.py modified into Valid.ipynb
  PYTHON/Valid.ipynb
  PYTHON/valid.py
Labels: Hacktoberfest-accepted

#27 Corrected prrogramme to programme
  C/Readme.md
Labels: Hacktoberfest-accepted

#28 Add files via upload
  C/Alphabetic_sorting_of_Names.c
Labels: good first issue, Hacktoberfest-accepted

#29 Add files via upload
  perfect_number.c
Labels: Hacktoberfest-accepted

#32 shuffle a deck of cards
  PYTHON/shuffle card.py
  shuffle.ipynb
Labels: Hacktoberfest-accepted

#33 Temperature Scale Convertor
  JAVA/Temperature_Scale_Converter.java
Labels: Hacktoberfest-accepted

#34 Add files via upload
  octal to decimal.c
Labels: Hacktoberfest-accepted

#35 Add files via upload
  C/perfect_number.c
Labels: Hacktoberfest-accepted

#38 Add files via upload
  C/fibonacci.c
Labels: Hacktoberfest-accepted

#37 perfect_number
  C/perfect_number.c
  perfect_number.c
Labels: Hacktoberfest-accepted

#39 inserted shuffle.ipynb into the PYTHON folder
  PYTHON/shuffle.ipynb
Labels: Hacktoberfest-accepted

#40 Count using python
  PYTHON/count.py
Labels: Hacktoberfest-accepted

#41 HelloWorld
  PYTHON/File.ipynb
  PYTHON/Stack_Operations_Using_Python.ipynb
Labels: Hacktoberfest-accepted

#42 Queue
  PYTHON/Queue_Operations_in_Stack.ipynb
Labels: Hacktoberfest-accepted

#43 Sample Using Python
  PYTHON/Concatenation_String_Sample.ipynb
Labels: Hacktoberfest-accepted

#44 Created
  PYTHON/Sort_in_python_Sample.ipynb
Labels: Hacktoberfest-accepted

#45 added battery monitor
  PYTHON/Batttery monitor/audio/mixkit-positive-notification-951.wav
  PYTHON/Batttery monitor/audio/mixkit-wrong-answer-fail-notification-946.wav
  PYTHON/Batttery monitor/batterymonitor.py
  PYTHON/Batttery monitor/pics/icon.png
Labels: Hacktoberfest-accepted

#46 added instagram scrapper
  PYTHON/instagram scrapper/requirements.txt
  PYTHON/instagram scrapper/scrapper.py
Labels: Hacktoberfest-accepted

#47 palindrome
  PYTHON/check_palindrome.py
Labels: Hacktoberfest-accepted

#48 added word cloud script
  PYTHON/word cloud/requirements.txt
  PYTHON/word cloud/wc.py
Labels: Hacktoberfest-accepted

#49 added basic calculator script
  PYTHON/calculator/calacimg.png
  PYTHON/calculator/main.py
Labels: Hacktoberfest-accepted

#50 player_number
  PYTHON/chest_number.py
Labels: Hacktoberfest-accepted

#51 Array Comparison
  PYTHON/array_comparison.py
Labels: Hacktoberfest-accepted

#52 Dictionary_Operations
  PYTHON/DictionaryOperations.ipynb
Labels: Hacktoberfest-accepted

#54 Add files via upload
  C/square.c
Labels: Hacktoberfest-accepted

#55 Add files via upload
  C/cube.c
Labels: Hacktoberfest-accepted

#56 Add files via upload
  C/perfectsquare.c
Labels: Hacktoberfest-accepted

#57 Add files via upload
  C/perfectcube.c
Labels: Hacktoberfest-accepted

#58 Add files via upload
  JAVA/amicable.java
Labels: Hacktoberfest-accepted

#59 Add files via upload
  decimaltooctal.java
Labels: Hacktoberfest-accepted

#62 Add files via upload
  JAVA/armstrong.java
Labels: Hacktoberfest-accepted

#64 Add files via upload
  JAVA/binarytodecimal.java
Labels: Hacktoberfest-accepted

#65 CeaserCipher
  PYTHON/CeaserCipher.ipynb
Labels: Hacktoberfest-accepted

#66 odd or even
  C/ODDSEVENS.c
Labels: Hacktoberfest-accepted

#67 dance moves
  C/DANCEMOVES.c
  C/TESTSERIES.c
Labels: Hacktoberfest-accepted

#69 badminton
  C/BADMINTON.c
Labels: Hacktoberfest-accepted

#70 drunk person
  C/DRUNKALK.c
Labels: Hacktoberfest-accepted

#72 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#71 evenodd.java
  C/leapyear.c
  JAVA/evenodd.java
Labels: Hacktoberfest-accepted

#73 Added a python string encryption
  PYTHON/encryption.py
Labels: Hacktoberfest-accepted

#74 guessgame.py
  PYTHON/guessgame.py
Labels: Hacktoberfest-accepted

#75 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#76 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#79 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#86 Add files via upload
  MagicNumber.c
Labels: Hacktoberfest-accepted

#81 search.py
  PYTHON/duplicate.py
  PYTHON/perfect.py
  PYTHON/search.py
Labels: Hacktoberfest-accepted

#85 Numpy Tutorials
  PYTHON/NumPy/#1Creating_Arrays.ipynb
  PYTHON/NumPy/#2ArrayIndexing.ipynb
Labels: Hacktoberfest-accepted

#84 Create pizza-cutter.cpp
  C++/pizza-cutter.cpp
Labels: Hacktoberfest-accepted

#83 Gaius code
  PYTHON/gaius-code.py
Labels: Hacktoberfest-accepted

#82 Ascii dancer
  PYTHON/ascii-dancer.py
Labels: Hacktoberfest-accepted

#80 Create MyTreat.py
  PYTHON/MyTreat.py
Labels: Hacktoberfest-accepted

#87 Add files via upload
  C/BuzzNumber.c
Labels: Hacktoberfest-accepted

#88 Updated Readme
  README.md
Labels: Hacktoberfest-accepted

#90 A snake game using turtle
  PYTHON/snakeGame.py
Labels: Hacktoberfest-accepted

#89 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#91 Add files via upload
  library.txt
  unscram.c
Labels: Hacktoberfest-accepted

#92 Add files via upload
  half pyramid numbers.c
Labels: Hacktoberfest-accepted

#95 Create Rotting__Oranges.cpp
  C++/Rotting__Oranges.cpp
Labels: Hacktoberfest-accepted

#94 A program that manages student records
  C/student.c
Labels: Hacktoberfest-accepted

#93 Add files via upload
  Compound interest.py
  PYTHON/lottery.py
  PYTHON/vowels.py
Labels: Hacktoberfest-accepted

#96 prg to find a number is positive or negative
  C/positiveornegative.c
Labels: Hacktoberfest-accepted

#97 Add files via upload
  C/lsdassignment.c
Labels: Hacktoberfest-accepted

#98 simple calculator
  C/calculator.c
  C/roots.c
Labels: Hacktoberfest-accepted

#99 Alphabet or not
  C/alphabet.c
Labels: Hacktoberfest-accepted

#103 Half
  C/half pyramid numbers.c
Labels: Hacktoberfest-accepted

#102 duplicate.py
  PYTHON/duplicate.py
Labels: Hacktoberfest-accepted

#100 Add files via upload
  armstrong.c
Labels: Hacktoberfest-accepted

#104 Created using Colaboratory
  PYTHON/compound interest.ipynb
Labels: Hacktoberfest-accepted

#101 Lucky 7 GAME in python
  PYTHON/diy.py
Labels: Hacktoberfest-accepted

#105 Quadratic eqn
  C/Quadratic eqn.c
  C/half pyramid alphabets.c
Labels: Hacktoberfest-accepted

#106 HTML File Creation
  HTML/HTML_File_Creation.html
Labels: Hacktoberfest-accepted

#107 Basic structure of HTML file creation
  HTML/HTML Basic Structure Creation.html
Labels: Hacktoberfest-accepted

#108 no of digits
  C/digit.c
Labels: Hacktoberfest-accepted

#111 to finf npr and nCr permutation and combination
  C/permutation.c
Labels: Hacktoberfest-accepted

#112 Dec_to_binary
  C/dec_to_binary.c
Labels: Hacktoberfest-accepted

#114 deletevow
  C/delete vowel.c
Labels: Hacktoberfest-accepted

#113 Calendar
  C/Calendar. C.pdf
Labels: Hacktoberfest-accepted

#115 removespace
  remove space.c
Labels: Hacktoberfest-accepted

#118 stddeviation
  C/standard deviation.c
Labels: Hacktoberfest-accepted

#117 100prime
  100prime.c.pdf
Labels: Hacktoberfest-accepted

#119 removespc
  C/remove space.c
Labels: Hacktoberfest-accepted

#120 100prime
  C/100prime.c.pdf
Labels: Hacktoberfest

#123 Add files via upload
  JAVA/binarysearch.java
Labels: Hacktoberfest

#122 Reversenum
  Reversenum.c.pdf
Labels: Hacktoberfest

#125 Ak new branch
  C/fullpyramidof*.c
  JAVA/bubble_sort.java
  JAVA/cyclic_sort.java
  JAVA/insertion_sort.java
  JAVA/selection_sort.java
Labels: Hacktoberfest

#124 neon
  C/neon.c
Labels: Hacktoberfest

#126 Add files via upload
  C/DuckNumber.c
Labels: Hacktoberfest

#127 Added sorting questions with solution and link.
  JAVA/DuplicateNum.java
  JAVA/FindAllDuplicates.java
  JAVA/FindAllMissingNumbers.java
  JAVA/find_missing_element.java
Labels: Hacktoberfest-accepted, Hacktoberfest

#129 Add files via upload
  C/HotelManagement.c
Labels: Hacktoberfest

#131 A NumPy tutorial#3
  PYTHON/_3ArraySlicing.ipynb
  RUST/binaryTree.c
Labels: Hacktoberfest2022

#132 Add files via upload
  C/set_op.c
Labels: Hacktoberfest-accepted

#134 Add files via upload
  C/anagram.c
  C/roman.c
Labels: Hacktoberfest-accepted, Hacktoberfest

#133 Program to sort names
  C++/main.cpp
  JAVA/numpat.java
  Welcome_To_Colaboratory.ipynb
Labels: Hacktoberfest-accepted

#138 Add files via upload
  C/patterns.c
Labels: good first issue, Hacktoberfest-accepted, Hacktoberfest

#137 Program to print K shape
  JAVA/kshape.java
  PYTHON/perrank.ipynb
  PYTHON/ranksort.py.txt
  persort.ipynb
Labels: Hacktoberfest-accepted, Hacktoberfest

#140 Kaprekar.java
  kaprekar.java
Labels: Hacktoberfest-accepted

#142 Add files via upload
  C/parenthesis_checking.c
Labels: Hacktoberfest-accepted

#136 program to find anagram strings
  C/interporationalsearch.c
Labels: Hacktoberfest-accepted

#145 Create MessageCountOnWhatsapp.py
  PYTHON/MessageCountOnWhatsapp.py
Labels: Hacktoberfest-accepted

#147 Added fashion_mnist_classification
  PYTHON/fashion_mnist_classification.ipynb
Labels: Hacktoberfest-accepted

#141 Library System code added
  C++/Readme.md
  C++/library_system.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest

#144 Create interest.c
  C/interest.c
Labels: Hacktoberfest-accepted

#146 Add files via upload
  lcm.c
  list_files.c
  reverse_string.c
Labels: Hacktoberfest-accepted

#148 Add files via upload
  C/lcm.c
  C/reverse_string.c
Labels: Hacktoberfest-accepted, Hacktoberfest

#149 Add files via upload
  C/exponent.c
  C/list_files.c
Labels: Hacktoberfest-accepted

#150 Add files via upload
  C/l_and_s.c
Labels: Hacktoberfest-accepted

#153 Add files via upload
  C/rev_file.c
Labels: Hacktoberfest-accepted

#155 Add files via upload
  C/simple_interest.c
  C/sum_of_digits.c
  C/triangle.c
Labels: Hacktoberfest-accepted

#154 Added DoublyLinkedList.ipynb
  PYTHON/DoublyLinkedList.ipynb
Labels: Hacktoberfest-accepted, Hacktoberfest

#158 Create MinStack.cpp
  C++/MinStack.cpp
Labels: Hacktoberfest-accepted

#157 Create factorial_calculation.cpp
  C++/factorial_calculation.cpp
Labels: Hacktoberfest-accepted

#156 Create NextGreater_element.cpp
  C++/NextGreater_element.cpp
Labels: Hacktoberfest-accepted

#159 Create Check_Leap_Year.cpp
  Check_Leap_Year.cpp
Labels: Hacktoberfest-accepted, Hacktoberfest

#160 Add files via upload
  C++/quotient.cpp
Labels: Hacktoberfest-accepted

#162 Input file to folder
  C++/Check_Leap_Year.cpp
  C/unscram.c
Labels: enhancement, Hacktoberfest-accepted

#161 Add files via upload
  C++/fibinacci.cpp
  C++/power.cpp
Labels: Hacktoberfest-accepted

#163 uploading rust programs
  RUST/38.pdf
  RUST/convertTime.rs
  RUST/cpuCores.rs
  RUST/randomNumber.rs
  RUST/sortVector.rs
Labels: Hacktoberfest-accepted

#164 Add files via upload
  C++/lexicographical_order.cpp
Labels: Hacktoberfest-accepted

#165 DecodeBase64 program
  RUST/decodeBase.rs
Labels: Hacktoberfest-accepted

#166 added is-anagram.py
  PYTHON/is-anagram.py
Labels: Hacktoberfest-accepted

#167 Input file to folder
  C/1-armstrong.c
  C/lcm_1.c
  C/list_files_1.c
  C/remove_space.c
  C/reverse_string_1.c
  JAVA/kaprekar.java
  PYTHON/Compound interest.py
  PYTHON/persort.ipynb
Labels: Hacktoberfest-accepted

#168 ASCII Code obtainer
  C/ASCII.c
Labels: Hacktoberfest-accepted

#169 distance bw 2 points program
  RUST/distancebw2points.rs
Labels: Hacktoberfest-accepted

#170 Extract Url scheme program
  RUST/extractUrl.rs
Labels: Hacktoberfest-accepted

#173 Reversenum
  Reversenum.c
Labels: Hacktoberfest-accepted

#175 100prime
  100prime.c
Labels: Hacktoberfest-accepted

#174 CGPA & Percentage Calculator
  C++/cgpaper.cpp
Labels: Hacktoberfest-accepted

#176 added article summarization.ipynb
  article_summarization.ipynb
Labels: Hacktoberfest-accepted, Hacktoberfest

#177 Calendar
  C/Calendar.c
Labels: Hacktoberfest-accepted

#178 bin
  C/bin_to_decimal.c
Labels: Hacktoberfest-accepted

#179 binary
  C/binary_to_octal.c
Labels: Hacktoberfest-accepted

#180 dec
  C/decimal_to_octal.c
Labels: Hacktoberfest-accepted

#181 string
  C/frequency_of_characters_in_a_string.c
Labels: Hacktoberfest-accepted

#182 Added Password generator program
  PYTHON/password_generator.py
Labels: Hacktoberfest-accepted

#183 age
  C/agecalculator.c
Labels: Hacktoberfest-accepted
